name: Genesis
version: '${version}'
main: tv.galaxe.genesis.Core
api-version: 1.20
authors: [ josefbaltz, garrettsummerfi3ld ]
depend: [ LuckPerms ]
description: A Minecraft server plugin inspired by the Origins mod.
website: https://github.com/GalaxeTV/genesis
commands:
  genesis:
    description: Genesis Help Menu
    usage: "Usage: /<command>"
    aliases: [gen, g]
    default: true
  genesisreload:
    description: Reload config file
    usage: "Usage: /<command>"
    default: op
    permission: genesis.reload
permissions:
  genesis.classes.skeleton:
    description: Permission indicating the player has chosen the skeleton class.
  genesis.classes.enderman:
    description: Permission indicating the player has chosen the enderman class.
  genesis.classes.phantom:
    description: Permission indicating the player has chosen the phantom class.
  genesis.reload:
    description: Permission for reloading config file.
    default: op
