blank_issues_enabled: false
contact_links:
  - name: Galaxe's Spaceship (Discord)
    url: https://discord.com/invite/galaxe
    about: For SMP related questions, please join our Discord server. Do not use GitHub Issues for GalaxeSMP specific questions.