# This workflow applies formatted syntax of the code using spotless.
name: Syntax Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}+${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "spotless"
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      # Setup Java 17
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.0.0

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Runs our formatter for easier code review
      - name: Run spotlessApply
        run: ./gradlew spotlessApply

      # Check if there are any changes, if so, create a commit and push it
      - name: Create commit of formatted code
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "[Spotless] Apply formatting"